### ISSUE TITLE
Duplicate URL

### ISSUE THREAD

**Issue by k-ebu** [EugenMayer/helm-charts#31]
When Ingress is directed to backend or to nginx, the URLs are duplicated as follows.

If I access to `http://rundeck.xxx.xxx.xxx.xxx.sslip.io/`, redirected to `http://rundeck.xxx.xxx.xxx.xxx.sslip.io/rundeck.xxx.xxx.xxx.xxx.sslip.io/menu/home`.

**Comment by EugenMayer** [comment]
Please add far more analysis and logs to that issue.

**Comment by k-ebu** [comment]
When I change the `externUrl`, the redirect url is also changed.

`http://{ingress.hosts.host}/{externUrl}/menu/home`

**Comment by k-ebu** [comment]
`externUrl`: `rundeck-backend`
`ingress.hosts.host`: `rundeck.xxx.xxx.xxx.xxx.sslip.io`

When I access to `rundeck.xxx.xxx.xxx.xxx.sslip.io`, chrome dev tool return `302 Found`.
And redirect to `http://rundeck.xxx.xxx.xxx.xxx.sslip.io/user/login`

Enter `Log in`, accress to `http://rundeck.xxx.xxx.xxx.xxx.sslip.io/j_security_check` return `302 Found` and redirect to `http://rundeck.xxx.xxx.xxx.xxx.sslip.io/`.
And return `302 Found` and redirect to `http://rundeck.xxx.xxx.xxx.xxx.sslip.io/rundeck-backend/menu/home`.
Then return `404 Not Found`.

**Comment by k-ebu** [comment]
I can login by entering `http://rundeck.xxx.xxx.xxx.xxx.sslip.io/menu/home` directly in browser's URL.
However, if I then select a project, I get the following and a 404 is returned.

`http://{ingress.hosts.host}/{externUrl}/project/test_project/home`


If I create a job while manually modifying the URL, 404 is returned with the following URL.

`http://{ingress.hosts.host}/project/test_project/job/{externUrl}/job/show/213bfcfc-b007-4c7b-91ff-0c1465a53f1c`

**Comment by k-ebu** [comment]
This issue has been resolved.
It worked fine when externUrl was set to `http://rundeck.xxx.xxx.xxx.xxx.sslip.io`, not `rundeck.xxx.xxx.xxx.xxx.sslip.io`.

**Comment by EugenMayer** [comment]
Your externURL has to match your external URL including the schema.

So if you access your rundeck using https://foo.tld this is what you need to have in your externURL
