### ISSUE TITLE
Syntax issues in rundeck/templates/rundeck-backend-deployment.yaml prevent nodeSelector and more from working

### ISSUE THREAD

**Issue by dustinrue** [EugenMayer/helm-charts#33]
While trying to deploy to a single AZ on AWS I ran into a syntax issue with this file. PR #32 fixes the issue.

**Comment by EugenMayer** [comment]
Thank your for going right for the PR, very appropriated.

**Comment by EugenMayer** [comment]
Released with 1.3.1
