### ISSUE TITLE
Rundeck Helm Chart

### ISSUE THREAD

**Issue by armenr** [EugenMayer/helm-charts#38]
Hi Eugen - 

I'm sorry for polluting your repo's GitHub issues...but I honestly just wanted to say thank you for the labor of love and all the effort you've put into your Rundeck helm chart.

It's great, and you deserve some credit (and a high five ✋🏼).

Thank you,
_A fan.

**Comment by EugenMayer** [comment]
Thank you for the kind words! Very appreciated!

**Comment by fdevans** [comment]
Agreed!  Double high-five from me too!  @EugenMayer  I sent you a message on LinkedIn, look forward to connecting.
