### ISSUE TITLE
stuck at login when running multiple pods

### ISSUE THREAD

**Issue by vineetmadan** [EugenMayer/helm-charts#46]
Everything works fine with 1 pod. But when I run more than 1 pod, Rundeck is virtually stuck at the login page even when I'm entering the correct credentials. Even if I can log in after multiple attempts, I'm redirected to the login page when I click on anything.

Is there an explanation for this or is it some sort of bug?

**Comment by EugenMayer** [comment]
Sorry, cannot provide software or debugging support in the helm chart - this is out of scope. Please ask on the rundeck resources.

**Comment by vineetmadan** [comment]
Sorry, I should have made it more clear. In the readme, the description for parameter "deployment.replicaCount" suggests "Rundeck can really only work with one". Gave me the impression this is a known issue.

**Comment by EugenMayer** [comment]
If and how rundeck can work clustered / multihead is something you have to look up in the actual rundeck docs. You cannot scale and app horizontally if it does not support it.

I added a hint in the values now, but i guess this can and will happend over and over again. This chart does not aim to allow the user to skip reading the rundeck docs or what rundeck supports. This helm chart gives you maybe more freedome that might be allowed in rundeck, so one needs to read the docs and limit "yourself" to what is allowed.
