### ISSUE TITLE
Rundeck: Incorrect Mount Path for Plugins

### ISSUE THREAD

**Issue by pavankumar-go** [EugenMayer/helm-charts#54]
Hello,

Issue: Had to reinstall few plugins which got removed upon pod restart when PVC was enabled

Reason:
[README.md](https://raw.githubusercontent.com/EugenMayer/helm-charts/main/charts/rundeck/README.md) says for
`plugins.claim.enabled` -> `If enabled, mounts a volume for the plugins. Those will be copied to /home/rundeck/libexex/`

But the volume mount path is different in the rundeck deployment.yaml https://github.com/EugenMayer/helm-charts/blob/main/charts/rundeck/templates/rundeck-backend-deployment.yaml#L99 `/mnt/plugins`

**Comment by EugenMayer** [comment]
Hey @pavankumar-go, thanks for the find. Why not do a PR if you found all the bits already?

**Comment by pavankumar-go** [comment]
Okay, yeah sure.
