### ISSUE TITLE
[bug] - Rundeck backend deployment does not match healthcheck

### ISSUE THREAD

**Issue by castaway2000** [EugenMayer/helm-charts#56]
when deploying healthchecks in the backend file it does not use the nginx health endpoint as shown in the code where it says the healthcheck for the backend should use the nginx endpoint. This is unclear in the docs. took me a few days of troubleshooting. Alternatively we could turn off the healthchecks for the backend. thoughts? I'm curious how you expected people would deploy this? I am using helm install from the registry however it's not templated in the values file but it could be as a fix. Thoughts?

https://github.com/EugenMayer/helm-charts/blob/e00041c3590cad19ba9e36d60c8c50bca706e2df/charts/rundeck/files/nginx/nginx.conf#L11

https://github.com/EugenMayer/helm-charts/blob/e00041c3590cad19ba9e36d60c8c50bca706e2df/charts/rundeck/templates/rundeck-backend-deployment.yaml#L127

**Comment by EugenMayer** [comment]
Sorry, i cannot follow in any way. The live/readness probes are working as expected. They are defined on the rundeck pod and check the health of rundeck.]

Not really sure what you first link refers too
